select *
from ZAKAZ

--1.
--select prod, city
--from ZAKAZ

--2.
--SELECT city, name
--FROM zakaz

--3.
--SELECT NAME, KOD
--FROM ZAKAZ
--WHERE KOD == 1005

--4.
--SELECT NAME, RATING
--FROM ZAKAZ
--WHERE RATING > 380

--5.
--SELECT NAME, REM
--FROM ZAKAZ
--WHERE REM is Null

--6.
--SELECT KOD, SUM
--FROM ZAKAZ
--WHERE SUM > 4000

--7.
--SELECT NAME, SUM, CITY
--FROM ZAKAZ
--WHERE SUM<1000 AND CITY != "Иркутск"

--8.
--SELECT NAME, RATING
--FROM ZAKAZ
--WHERE RATING BETWEEN 100 AND 271

--9.
--SELECT NAME, KOD, CITY, CITY2
--FROM ZAKAZ
--WHERE CITY != CITY2

--10.
--SELECT KOD, RATING
--FROM ZAKAZ
--WHERE RATING < 200 OR RATING > 350

--11.
--SELECT NAME, PROD
--FROM ZAKAZ
--WHERE PROD == "столы обеденные"

--12.
--SELECT NAME
--FROM ZAKAZ
--WHERE NAME LIKE "%а%а%"

--13.
--SELECT NAME, KOD
--FROM ZAKAZ
--WHERE NAME LIKE "К%"

--14.
--SELECT KOD, CITY2, PROD
--FROM ZAKAZ
--WHERE PROD == "стулья" AND CITY2 = "Химки"

--15.
--SELECT NAME, CITY2, SUM
--FROM ZAKAZ
--WHERE CITY == CITY2 AND SUM BETWEEN 1000 AND 1751

--16.
--SELECT NAME
--FROM ZAKAZ
--WHERE PROD != "сейфы"

--17.
--SELECT NAME, PROD
--FROM ZAKAZ
--WHERE PROD == "диваны" AND SUM > 4000

--18.
--SELECT NAME, PROD, SUM
--FROM ZAKAZ
--WHERE PROD == "стулья" AND SUM > 1200

--19.
--SELECT NAME, RATING, CITY
--FROM ZAKAZ
--WHERE CITY != "Иркутск" AND RATING < 200 

--20.
--SELECT NAME, REM
--FROM ZAKAZ
--WHERE REM == "льготная доставка"

--21.
--SELECT NAME, CITY, SUM
--FROM ZAKAZ
--WHERE SUM > 14000 AND (CITY !="Москва" AND CITY != "Липецк")