# Generated by Django 4.2.2 on 2023-07-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_skills_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='skills',
            name='image',
            field=models.ImageField(blank=True, upload_to='skills/images/'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
