# Generated by Django 4.2.2 on 2023-07-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0004_alter_skills_description_alter_skills_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
